services:
  backend:
    build:
      context: 
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  frontend:
    build:
      context: ./front-end/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - 3000
